/**
 * @file Constants.h
 * @brief Constants Declaration.
 */

#ifndef CONSTANTS_DEFS_H_
#define CONSTANTS_DEFS_H_

typedef enum {
  BINOP_INVALID,
  ADD, SUB, MUL, UDIV, SDIV, UREM, SREM,
  FADD, FSUB, FMUL, FDIV, FREM,
  SHL, LSHR, ASHR, AND, OR, XOR
} BINOP;

typedef enum {
  CASTOP_INVALID,
  BITCAST, TRUNC, ZEXT,
  FPEXT, FPTOSI, FPTOUI, FPTRUNC,
  INTTOPTR, PTRTOINT,
  SEXT, SITOFP, UITOFP
} CASTOP;

typedef enum {
  UNINTERPRETEDINST_INVALID,
  EXTRACTELEMENT, INSERTELEMENT, SHUFFLEVECTOR,
  INSERTVALUE,
  UNREACHABLE, RESUME, INVOKE,
  SELECT, LANDINGPAD,
  FENCE,
  VAARG,
  ATOMICRMW
} UNINTERPRETEDINST;

typedef enum {
  // not implemented yet
} MACHINEFLAG;

typedef enum {
  REGISTER,
  LOCAL,
  GLOBAL
} SCOPE;

#endif /* CONSTANTS_DEFS_H_ */
